import { CATEGORYENUM, Project } from '../types';
import uuids from './uuids';

export const allProjects: Project[] = [
  {
    id: uuids[1],
    name: 'Tic Tac Toe',
    description:
      'A simple and interactive Tic Tac Toe game built with React and Vite. Play against a friend in the browser with a clean UI and instant feedback.',
    category: [CATEGORYENUM.GAME_DEVELOPMENT, CATEGORYENUM.WED_DEVELOPMENT],
    tags: ['React', 'Vite', 'JavaScript (ES6+)', 'SCSS', 'Node.js'],
    image: '/projects/tic-tac-toe.png',
    source_code_link: 'https://github.com/hemanthbabu648/tic-tac-toe',
    live_url: 'https://tic-tac-toe-hemanthbabu170648.vercel.app',
    position: 1,
  },
  {
    id: uuids[2],
    name: 'Personal Portfolio',
    description:
      'A responsive and modern personal portfolio website built to showcase my projects, skills, and experience. Designed with clean UI/UX principles and developed using [HTML, CSS, JavaScript, React, Next JS, Framer Motion, TailWind CSS etc.], this site serves as a central hub for my online presence and professional work.',
    category: [CATEGORYENUM.PORTFOLIO, CATEGORYENUM.WED_DEVELOPMENT],
    tags: ['React', 'Next JS', 'Framer Motion', 'Tailwind CSS'],
    image: '/projects/hemanthbabu648.png',
    source_code_link: 'https://github.com/hemanthbabu648/hemanthbabu648',
    live_url: 'https://hemanthbabu648.com',
    position: 2,
  },
  {
    id: uuids[3],
    name: 'Finance Tracker',
    description: 'A comprehensive finance tracker to manage your expenses and income effectively.',
    category: [CATEGORYENUM.FINANCE, CATEGORYENUM.WED_DEVELOPMENT],
    tags: ['React', 'Node.js', 'Supabase ', 'Express', 'Tailwind CSS', 'TypeScript'],
    image: '/projects/finance-tracker.png',
    live_url: 'https://finance-tracker-fsdhemanth648.vercel.app/',
    position: 3,
  },
  {
    id: uuids[4],
    name: 'Blog Platform',
    description: 'A full-featured blogging platform with markdown support.',
    category: [CATEGORYENUM.BLOGS, CATEGORYENUM.WED_DEVELOPMENT],
    tags: ['React', 'Next.js', 'Mdx', 'Tailwind CSS'],
    image: '/projects/mdx-blog.png',
    source_code_link: 'https://github.com/hemanthbabu648/mdx-blog',
    live_url: 'https://blogs.hemanthbabu648.com/',
    position: 4,
  },
  {
    id: uuids[5],
    name: 'E-Commerce Platform',
    description: 'A scalable e-commerce platform with payment integration.',
    category: [CATEGORYENUM.E_COMMERCE],
    tags: ['Next.js', 'Stripe', 'MongoDB'],
    image: 'https://www.hemanthbabu648.com/images/Projects/e-commerce.png',
    source_code_link: 'https://github.com/fsdhemanth648/e-commerce',
    live_url: '',
    position: 5,
  },
  {
    id: uuids[6],
    name: 'Mobile Fitness App',
    description: 'A cross-platform mobile app for tracking workouts and nutrition.',
    category: [CATEGORYENUM.MOBILE_DEVELOPMENT, CATEGORYENUM.HEALTHCARE],
    tags: ['React Native', 'Expo', 'Redux'],
    image: 'https://www.hemanthbabu648.com/images/Projects/fitness-app.png',
    source_code_link: '',
    live_url: '',
    position: 6,
  },
  {
    id: uuids[7],
    name: 'Game Leaderboard',
    description: 'A real-time leaderboard for multiplayer games.',
    category: [CATEGORYENUM.GAME_DEVELOPMENT, CATEGORYENUM.SOCIAL_MEDIA],
    tags: ['Socket.io', 'Node.js', 'React'],
    image: 'https://www.hemanthbabu648.com/images/Projects/game-leaderboard.png',
    source_code_link: '',
    live_url: '',
    position: 7,
  },
];
