import { CATEGORYENUM, Project } from '../types';
import uuids from './uuids';

export const allProjects: Project[] = [
  {
    id: uuids[1],
    name: 'Tic Tac Toe',
    description:
      'A simple and interactive Tic Tac Toe game built with React and Vite. Play against a friend in the browser with a clean UI and instant feedback.',
    category: [CATEGORYENUM.GAME_DEVELOPMENT, CATEGORYENUM.WED_DEVELOPMENT],
    tags: ['React', 'Vite', 'JavaScript (ES6+)', 'SCSS', 'Node.js'],
    image: '/projects/tic-tac-toe.png',
    source_code_link: 'https://github.com/hemanthbabu648/tic-tac-toe',
    live_url: 'https://tic-tac-toe-hemanthbabu170648.vercel.app',
    position: 1,
  },
  {
    id: uuids[2],
    name: 'Portfolio',
    description:
      'A responsive and modern personal portfolio website built to showcase my projects, skills, and experience. This site serves as a central hub for my online presence and professional work.',
    category: [CATEGORYENUM.PORTFOLIO, CATEGORYENUM.WED_DEVELOPMENT, CATEGORYENUM.SOCIAL_MEDIA],
    tags: ['React', 'Next JS', 'antd', 'mongoose', 'react-hook-form', 'react-to-pdf'],
    image: '/projects/portfolio.png',
    source_code_link: 'https://github.com/hemanthbabu648/portfolio',
    live_url: 'https://portfolio-hemanthbabu170648.vercel.app',
    position: 2,
  },
  {
    id: uuids[3],
    name: '3d Portfolio',
    description:
      'A responsive and modern personal 3d-portfolio website built to showcase my projects, skills, and experience. This site serves as a central hub for my online presence and professional work.',
    category: [CATEGORYENUM.PORTFOLIO, CATEGORYENUM.WED_DEVELOPMENT, CATEGORYENUM.SOCIAL_MEDIA],
    tags: [
      'React',
      'Next JS',
      'Framer Motion',
      'Tailwind CSS',
      'react-tilt',
      'react-horizontal-timeline',
      'react-vertical-timeline-component',
      'emailjs/browser',
    ],
    image: '/projects/3d-portfolio.png',
    source_code_link: 'https://github.com/hemanthbabu648/3d-portfolio',
    live_url: 'https://3d-portfolio-hemanthbabu170648.vercel.app',
    position: 3,
  },
  {
    id: uuids[4],
    name: 'Apps Showcase',
    description: 'A cross-platform mobile app for tracking workouts and nutrition.',
    category: [CATEGORYENUM.WED_DEVELOPMENT],
    tags: [
      'React',
      'Next JS',
      'Mantine',
      'Tailwind CSS',
      'react-hook-form',
      'zod',
      'emailjs/browser',
    ],
    image: '/projects/apps-showcase.png',
    source_code_link: 'https://github.com/hemanthbabu648/apps.hemanthbabu648',
    live_url: 'https://apps.hemanthbabu648.com',
    position: 4,
  },
  {
    id: uuids[5],
    name: 'Blog Platform',
    description: 'A full-featured blogging platform with markdown support.',
    category: [CATEGORYENUM.BLOGS, CATEGORYENUM.WED_DEVELOPMENT],
    tags: [
      'React',
      'Next JS',
      'Mdx',
      'Tailwind CSS',
      'next-mdx-remote',
      'remark-html',
      'gray-matter',
      'react-hook-form',
      'zod',
      'emailjs/browser',
    ],
    image: '/projects/mdx-blog.png',
    source_code_link: 'https://github.com/hemanthbabu648/mdx-blog',
    live_url: 'https://blogs.hemanthbabu648.com',
    position: 5,
  },
  {
    id: uuids[6],
    name: 'Personal Finance Tracker',
    description: 'A comprehensive finance tracker to manage your expenses and income effectively.',
    category: [CATEGORYENUM.FINANCE, CATEGORYENUM.WED_DEVELOPMENT],
    tags: ['React', 'Node.js', 'Supabase ', 'Express', 'Tailwind CSS', 'TypeScript'],
    image: '/projects/finance-tracker.png',
    position: 6,
  },
];
